version: '3.7'

services:
  gitlab_task_manager:
    container_name: gitlab_task_manager
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
